import Head from "next/head";
import ImgButton from "@/components/donate/ImageButton/ImgButton";
import FormInput from "@/components/donate/ImageButton/Forms/FormInput";

/* TODO:
* Page Structure:
*  - complete rest of donate form
*  - update ImgButton component to change onclick (hooks?)
*  - create new component to link the states of individual ImgButtons together
*     - e.g. clicking on one ImgButton will disable/un-highlight the others
* CSS:
*  - polish up & mobile compatibility
*/

const formCSS = "border-2 border-gray-300 rounded-md px-1 py-1";

const formSettings = [
    {
        title: "Name",
        type: "text",
        tailwindCSS: formCSS,
    },
    {
        title: "Email",
        type: "text",
        tailwindCSS: formCSS,
    },
    {
        title: "Phone Number",
        type: "text",
        tailwindCSS: formCSS,
    },
];

const donationOptionSettings = [
    {
        text: "Donation Option 1",
        imageURL: "bg-[url('/images/dylan.png')]",
    },
    {
        text: "Donation Option 2",
        imageURL: "bg-[url('/images/dylan.png')]",
    },
    {
        text: "Donation Option 3",
        imageURL: "bg-[url('/images/dylan.png')]",
    },
];

export default function Donate() {
    return (
        <>
            <Head>
                <title>Gunn Alumni | Donate</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/dylan.png"/>
            </Head>
            <div className="w-screen box-border px-10 py-10 flex flex-col gap-y-4"> {/*Wrapper*/}
                <div className="flex flex-col w-full box-border rounded-xl h-[40vh]">
                    <h1 className="font-bold text-xl">Donation Options</h1>
                    <div className="w-full box-border grow flex items-stretch gap-2">
                        {donationOptionSettings.map((data, i) => (
                            <ImgButton
                                key={i}
                                text={data.text}
                                imageURL={data.imageURL}
                            />
                        ))}
                    </div>
                </div>
                <div className="flex flex-col box-border rounded-xl grow gap-y-2 h-[50vh]">
                    <form>
                        <div className="w-full box-border flex flex-col gap-y-4">
                            <h1 className="font-bold text-xl">Your Information</h1>
                            <div className="w-full grid grid-cols-2 gap-x-4 gap-y-2">
                                {formSettings.map((data, i) => (
                                    <FormInput
                                        key={i}
                                        title={data.title}
                                        type={data.type}
                                        tailwindCSS={data.tailwindCSS}
                                    />
                                ))}
                            </div>
                            <div className="flex justify-center">
                                <input type="submit" className="bg-primary font-bold text-white w-fit h-fit px-10 py-5 rounded-lg cursor-pointer"></input>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </>
    )
}