// React Components
import Head from "next/head";

export default function Home() {
  return (
    <>
        <Head>
        <title>Gunn Alumni | Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:mx-64">
        {/* Header */}


        <div className="m-5">
          <div className="flex justify-center">
            <div className="flex flex-col items-center bg-neutral-200 p-6 m-3 rounded-lg">
              <h1 className="pb-4 font-bold text-lg text-center">Welcome Gunn Alumni!</h1> 
              <p className="text-center">klsadfjadsjflkjsadlk  ajkdfsjfjaksld f;jk;ldsafjklajd klfjdsklfjaklj klaj kl jkl jfklj dklsjalfk jllkds jkl jklds sf</p>

              <button href="/classmates" className="text-white bg-red-500 hover:bg-red-500/90 mt-5 p-1 w-fit">See Classmates</button>
            </div>
            
            <div className="bg-neutral-200 p-32 m-3">image</div>
          </div>
        </div>

          {/* Main Content */}

          <div className="bg-gray-400 p-10">
            <h1 className="text-white font-bold pb-3">MMM CONTENT</h1>

            <div className="flex flex-wrap justify-center">
              <div className="bg-white m-2 p-5 ">content</div>

              <div className="bg-white m-2 p-5 ">content</div>

              <div className="bg-white m-2 p-5 ">content</div>
  
              <div className="bg-white m-2 p-5 ">content</div>

              <div className="bg-white m-2 p-5 ">content</div>

              <div className="bg-white m-2 p-5 ">content</div>

              <div className="bg-white m-2 p-5 ">content</div>
  
              <div className="bg-white m-2 p-5 ">content</div>
            </div>

            
          </div>


        </div>

          {/* Footer */}

            <div className="bg-gray-600 h-64 flex justify-center mt-6 items-center">

            <div></div>

            <div className="text-white font-bold"></div>
            </div>

    </>
  );
}
