import Head from "next/head";
import Image from "next/image";
import dylan from "../../public/images/dylan.png";

export default function Home() {
  return (
    <>
      <Head>
        <title>Gunn Alumni | Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-screen px-5 py-10">
        <div className="rounded-xl w-full md:flex">
          <div className="relative w-full h-[40vh] md:h-[80vh]">
            <Image
              src={dylan}
              alt="dylan"
              className="object-cover rounded-t-lg md:rounded-none md:rounded-l-lg"
              fill
            />
          </div>
          <div className="bg-primary text-white flex flex-col items-center p-8 rounded-b-lg md:rounded-none md:rounded-r-lg">
            <div className="font-bold text-xl text-center mb-5">
              Gunn Grad Dylan Cures Cancer with HTML
            </div>
            <div className="mb-5 flex-1">No one knows how he did it</div>
            <div className="flex justify-around w-full h-12 space-x-3">
              <button className="rounded-lg text-sm bg-black text-white font-bold flex-1">
                Read More
              </button>
              <button className="rounded-lg text-sm outline outline-2 outline-white text-white font-bold flex-1">
                Explore News
              </button>
            </div>
          </div>
        </div>
        <div></div>
      </div>
    </>
  );
}
